.github/pull_request_template.md

New Pull Request template that attempts to make sure we get good PRs.

Pull Request Template for Goatrodeo

---

build.sbt

What did you change, and what additional context do reviewers need?
Updated the email address that goes in as maintainer to docker container to "ext-engineering@spicelabs.io"
Why were these changes made? What tradeoffs were considered?
Discussion was had about what email we wanted to give to the public to contact us. this was the decided answer.
Beyond unit tests, how did you make sure this code is ready for production?
I emailed the email alias from ym personal email and it showed up ok.
n/a
EXEMPT, one line email address change.
Did you…
- Make sure any open comments or …

Update build.sbt contact email address to ext-engineering

---

build.sbt
info/hidden_reapers.md
src/main/scala/goatrodeo/Main.scala
src/main/scala/goatrodeo/omnibor/BuildGraph.scala
src/main/scala/goatrodeo/toplevel/HiddenReaper.scala
src/test/scala/HiddenReaperTests.scala
src/test/scala/MySuite.scala

Updated documentation. Added some case classes to make JSON more readable
Updated documentation based on Jenny's feedback on document readability
Added some case classes to avoid using Tuples (give names to things) and
to make the resulting JSON more readable
Updated tests to take into account new case classes
Substantial updates to hidden_reapers.md
Did you…
- [No ] Mention an issue number in the PR title?
- [ X] Update the version # in the build file?
- [ X] Create new and/or update relevant existing tests?
- [ X] Create or update relevant documentation and/or diagrams?
- [ X] Comment your code?
- [ X] Fix any stray verbose logging (removing, or moving to debug / trace level)?
- Make …

Maybe final build for Unmasking Hidden Reapers

---

README.md

A bit of a trivial change so most of the PR template doesn't apply 
Did you…

Correct link to omnibor glossary definition

---

build.sbt
src/main/resources/logback.xml

*What did you change, and what additional context do reviewers need?*
This updates logback from 1.2.10 to 1.5.12, and updates the default log level from `INFO` to `DEBUG`.
*Why were these changes made? What tradeoffs were considered?*
Tika brings in transitive dependencies on commons-logging 1.3.4 and slf4j-api 2.0.16:
```
[info]   | |   | +-commons-logging:commons-logging:1.2 (evicted by: 1.3.4)
[info]   | |   | +-commons-logging:commons-logging:1.3.4
```
```
[info]   | +-org.slf4j:slf4j-api:1.7.32 (evicted by: 2.0.16)
[info]   | +-org.slf4j:slf4j-api:2.0.16
```
This breaks the older commons-logging 1.2.10 and slf4j-api 1.7.5 that had been in use:
```
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See …
```

logback: 1.2.10 -> 1.5.12

---

.github/CODEOWNERS

Clean up codeowners

---

README.md
info/hidden_reapers.md

Cleaned up README.md file and updated the Hidden Reaper file
Requests from Cisco and general cleanup.
No code, only documentation changed
Updated the README file and added the the Hidden Reaper file
Did you…
- [No ] Mention an issue number in the PR title?
- [ N/A] Update the version # in the build file?
- [ N/A] Create new and/or update relevant existing tests?
- [ x] Create or update relevant documentation and/or diagrams?
- [ N/A] Comment your code?
- [ N/A] Fix any stray verbose logging (removing, or moving to debug / trace level)?

Updated documentation

---

RELEASE_PROCESS.md

Documented the release process
This is not fully tested -- would love to have it gone through to test it with a new release

doc: release process

---

src/main/scala/goatrodeo/omnibor/Builder.scala

Improved computation of items/minute and time remaining
Improve observability
passes tests
Did you…

Improved computation of items/minute and time remaining

---

src/main/scala/goatrodeo/omnibor/Builder.scala
src/main/scala/goatrodeo/util/FileWalker.scala

Set the "start of processing" after 30 items are processed
Don't try to decompress certain types.
Improve time estimation.
Don't try to decompress an APK that's an Android APK
Passes existing tests
Did you…

Improved the averaging code. Improved decompression

---

src/main/scala/goatrodeo/omnibor/strategies/Maven.scala

If the Maven manifest file, can't be parsed, ignore the parse error
The parse error was causing the whole JAR to fail
Runs existing tests
Did you…

Caught an issue if the props file can't be parsed

---

build.sbt
project/plugins.sbt
src/main/scala/goatrodeo/Main.scala
src/main/scala/goatrodeo/envelopes/Envelope.scala
src/main/scala/goatrodeo/omnibor/Builder.scala
src/main/scala/goatrodeo/omnibor/Cluster.scala
src/main/scala/goatrodeo/omnibor/GraphManager.scala
src/main/scala/goatrodeo/omnibor/Item.scala
src/main/scala/goatrodeo/omnibor/Storage.scala
src/main/scala/goatrodeo/omnibor/Struct.scala
src/main/scala/goatrodeo/omnibor/ToProcess.scala
src/main/scala/goatrodeo/omnibor/strategies/Debian.scala
src/main/scala/goatrodeo/omnibor/strategies/Generic.scala
src/main/scala/goatrodeo/omnibor/strategies/Maven.scala
src/main/scala/goatrodeo/util/ArtifactWrapper.scala
src/main/scala/goatrodeo/util/FileWalker.scala
src/main/scala/goatrodeo/util/Helpers.scala
src/main/scala/goatrodeo/util/PURLHelpers.scala
src/test/scala/ISOFileSuite.scala
src/test/scala/MySuite.scala

Fixed a memory retention bug
Updated some logging to make it cleaner
Ran scalafmt and scalafix on the code (thus every file is changed)
Unable to build ADGs for large data sets (e.g., 1.7M files)
Runs all current tests. Also built ADGs for 1.7M files

Fixed a memory retention bug

---

.github/workflows/scala_container_publishing.yml

Updated org token then changed the name of  {{ secrets.GITHUB_TOKEN }} secret to {{ secrets.GH_TOKEN }} because secrets with names starting with "GITHUB" errors out
What did you change, and what additional context do reviewers need?
Why were these changes made? What tradeoffs were considered?
Beyond unit tests, how did you make sure this code is ready for production?
Did you…

Changed name of Token

---

.github/workflows/scala_container_publishing.yml

Workflow file, secrets and variables
publishing was failing
In review
no documentation change yet
Did you…

Auth errors: goatrodeo issues 63

---

.github/workflows/scala_container_publishing.yml

Corrected steps and env variables to enable publishing to both dockerhub and ghcr.io
Why were these changes made? What tradeoffs were considered?
Goatrodeo will be opensourced and needs to be publicly avaliable
running workflow from branch was the test
Did you…

Publish Docker image #63

---

.github/workflows/scala_container_publishing.yml

Modified section: package scala application so save the JAR file
- name: Package Scala application
run: sbt package
- name: Save JAR artifact
uses: actions/upload-artifact@v4
with:
name: my-scala-app-${{ github.run_id }}
path: target/scala-*/goatrodeo*.jar

Added step to save JAR file

---

.github/workflows/native_container_publishing.yml

What did you change, and what additional context do reviewers need?
Why were these changes made? What tradeoffs were considered?
Beyond unit tests, how did you make sure this code is ready for production?
Did you…

local update to try multi-platform image docker build

---

maven/pom.xml
src/main/scala/io/spicelabs/goatrodeo/GoatRodeoBuilder.scala

Note: Please delete all instructional text (like this and the examples/prompts below) before submitting your PR. Keep only the information that’s relevant to your change.
---
Thanks for contributing to goatrodeo! If you've discussed these changes with our team already, you probably know whether this will be integrated. We'll try to coordinate with you as best we can to integrate your changes. If your changes are not aligned with our product direction, we reserve the right to reject them, take a different approach, or integrate the ideas in a different way. Thanks for participating!
---
The level of documentation in a PR should reflect the scope and impact of the change — use your judgment to decide what’s appropriate.
To help reviewers (and future readers), please review the guidance …

don't forget the pom. it has the deps.

---

.github/workflows/publish.yml

fix build perms

---

src/main/scala/io/spicelabs/goatrodeo/Main.scala
src/main/scala/io/spicelabs/goatrodeo/util/ArtifactWrapper.scala
src/main/scala/io/spicelabs/goatrodeo/util/Config.scala
src/main/scala/io/spicelabs/goatrodeo/util/StaticMetadata.scala
src/test/scala/DotNetTesting.scala

Issue #168 
When package URLs are invalid, they are logged at debug and no stack trace is logged.
Started a bit on #169

pURL failures from static metadata logged as debug.

---

README.md

Updated README to document mime filters.
This addresses [Issue #174](https://github.com/spice-labs-inc/goatrodeo/issues/174)

Added doc'n for mime filters
